server:
  port: 8082

eureka:
  client:
    initial-instance-info-replication-interval-seconds: 2

management:
  endpoints:
    web:
      expose: true
    configprops:
      enabled: true

endpoints:
  configprops:
    enabled: true