server:
  port: 8040
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vadimshavlovski/spring_microservices
          search-paths: config-repo
          username:                           #git login
          password:                           #git password

